name: BeaconLabsLobby
author: ItsBeacon
version: '${project.version}'
main: org.bcnlab.beaconlabslobby.BeaconLabsLobby
api-version: '1.21'
channels:
  - BungeeCord
commands:
  selector:
    usage: /selector
    description: Opens the server selector
  labslobby:
    usage: /labslobby
    description: Returns info about the plugin
  build:
    usage: /build
    description: Allows you to build
  spawn:
    usage: /spawn
    description: Teleports the sender to spawn
  setspawn:
    usage: /setspawn
    description: Sets the spawn for the lobby
  hider:
    usage: /hider
    description: Opens a GUI to hide other players
  refreshscoreboard:
    usage: /refreshscoreboard
    description: Refresh the scoreboard
    aliases: [refreshsb, resb]